export type Role = 'STUDENT' | 'DEANERY' | 'ADMINISTRATOR'

export type Faculty = 'MATHEMATICS' | 'INFORMATICS' | 'HUMANITIES' | 'NATURALSCIENCES' | 'ECONOMY' | 'ENGINEERING'

export type Career = 'CYBERSECURITY_ENGINEERING' | 'SYSTEMS_ENGINEERING' | 'ARTIFICIAL_INTELLIGENCE_ENGINEERING' | 'STATISTICAL_ENGINEERING'

export type State = 'PENDIENT' | 'INPROGRESS' | 'APPROVED' | 'REJECTED'

export type Status = 'APPROVED' | 'REPROVED' | 'INPROGRESS'